/* PROPOSED COPY — review only; not canonical localization. */
window.EVENT_COPY={
  "en": {
    "eventsV1Intro": "Find a moment that fits.",
    "eventsV1Loading": "Loading events…",
    "eventV1Loading": "Loading event…",
    "eventsV1EmptyTitle": "Nothing planned just yet.",
    "eventsV1EmptyBody": "Events will appear here when they’re available.",
    "eventsV1ErrorTitle": "Events aren’t available right now.",
    "eventsV1ErrorBody": "Please try again.",
    "eventsV1OfflineTitle": "You’re offline.",
    "eventsV1OfflineBody": "Reconnect to see the latest event details.",
    "eventV1UnavailableTitle": "This event isn’t available.",
    "eventV1UnavailableBody": "You can return to the events list.",
    "eventV1Back": "Back to events",
    "eventV1CategoryNetworking": "Networking",
    "eventV1CategorySocial": "Social",
    "eventV1CategoryActivity": "Activity",
    "eventV1CategoryLabel": "Category: {category}",
    "eventV1Start": "Starts",
    "eventV1End": "Ends",
    "eventV1Venue": "Venue",
    "eventV1About": "About this event",
    "eventV1YourChoice": "Your choice",
    "eventV1Interested": "Interested",
    "eventV1Going": "Going",
    "eventV1None": "No choice yet",
    "eventV1Withdraw": "Withdraw",
    "eventV1ChoiceHelp": "Only your own choice is shown here. Going does not check you in.",
    "eventV1Saving": "Updating your choice…",
    "eventV1SaveFailed": "Your choice couldn’t be updated. Please try again.",
    "eventV1SavedAnnouncement": "Your choice is now {choice}.",
    "eventV1WithdrawnAnnouncement": "Your choice has been withdrawn.",
    "eventV1Started": "Event started",
    "eventV1LockedBody": "Choices can no longer be changed after the event starts.",
    "eventV1Cancelled": "Cancelled",
    "eventV1CancelledBody": "This event has been cancelled. Event actions are unavailable.",
    "eventV1CancelledChoice": "Your previous choice: {choice}. It is no longer active.",
    "eventV1ChangedTitle": "Event details updated",
    "eventV1ChangedBody": "Review the latest information below.",
    "eventV1ChoiceKept": "Your choice is unchanged.",
    "eventV1Plan": "Make a plan",
    "eventV1Calendar": "Add to Calendar",
    "eventV1Map": "Open venue on map",
    "eventV1CalendarHelp": "Calendar entries won’t update automatically if event details change.",
    "eventV1CalendarOpening": "Opening your calendar…",
    "eventV1CalendarFailed": "Your calendar couldn’t be opened. Please try again.",
    "eventV1MapOpening": "Opening the venue on your map…",
    "eventV1MapFailed": "The map couldn’t be opened. Please try again.",
    "eventV1ReminderPush": "An event you’re going to starts soon.",
    "eventV1ChangedPush": "An event you chose has been updated.",
    "eventV1CancelledPush": "An event you chose has been cancelled.",
    "eventV1TimeZone": "Times shown in {zone}.",
    "eventV1ImageUnavailable": "Event image unavailable",
    "eventV1ListChoice": "Your choice: {choice}",
    "navProfile": "Profile",
    "navMessages": "Messages",
    "navNearby": "Nearby",
    "navEvents": "Events",
    "retry": "Try again"
  },
  "tr": {
    "eventsV1Intro": "Sana uyan bir an bul.",
    "eventsV1Loading": "Etkinlikler yükleniyor…",
    "eventV1Loading": "Etkinlik yükleniyor…",
    "eventsV1EmptyTitle": "Henüz bir etkinlik yok.",
    "eventsV1EmptyBody": "Etkinlikler hazır olduğunda burada görünecek.",
    "eventsV1ErrorTitle": "Şu an etkinliklere ulaşılamıyor.",
    "eventsV1ErrorBody": "Tekrar deneyebilirsin.",
    "eventsV1OfflineTitle": "Çevrimdışısın.",
    "eventsV1OfflineBody": "Güncel etkinlik bilgilerini görmek için yeniden bağlan.",
    "eventV1UnavailableTitle": "Bu etkinliğe ulaşılamıyor.",
    "eventV1UnavailableBody": "Etkinlik listesine dönebilirsin.",
    "eventV1Back": "Etkinliklere dön",
    "eventV1CategoryNetworking": "Networking",
    "eventV1CategorySocial": "Sosyal",
    "eventV1CategoryActivity": "Aktivite",
    "eventV1CategoryLabel": "Kategori: {category}",
    "eventV1Start": "Başlangıç",
    "eventV1End": "Bitiş",
    "eventV1Venue": "Mekân",
    "eventV1About": "Etkinlik hakkında",
    "eventV1YourChoice": "Tercihin",
    "eventV1Interested": "İlgileniyorum",
    "eventV1Going": "Gideceğim",
    "eventV1None": "Henüz bir tercih yok",
    "eventV1Withdraw": "Tercihimi geri çek",
    "eventV1ChoiceHelp": "Burada yalnız kendi tercihin görünür. Gideceğim seçeneği check-in yapmaz.",
    "eventV1Saving": "Tercihin güncelleniyor…",
    "eventV1SaveFailed": "Tercihin güncellenemedi. Tekrar deneyebilirsin.",
    "eventV1SavedAnnouncement": "Tercihin artık {choice}.",
    "eventV1WithdrawnAnnouncement": "Tercihin geri çekildi.",
    "eventV1Started": "Etkinlik başladı",
    "eventV1LockedBody": "Etkinlik başladıktan sonra tercihler değiştirilemez.",
    "eventV1Cancelled": "İptal edildi",
    "eventV1CancelledBody": "Bu etkinlik iptal edildi. Etkinlik işlemleri kullanılamıyor.",
    "eventV1CancelledChoice": "Önceki tercihin: {choice}. Artık geçerli değil.",
    "eventV1ChangedTitle": "Etkinlik bilgileri güncellendi",
    "eventV1ChangedBody": "Güncel bilgileri aşağıda inceleyebilirsin.",
    "eventV1ChoiceKept": "Tercihin değişmedi.",
    "eventV1Plan": "Planına ekle",
    "eventV1Calendar": "Takvime ekle",
    "eventV1Map": "Mekânı haritada aç",
    "eventV1CalendarHelp": "Etkinlik bilgileri değişirse takvim kaydı otomatik güncellenmez.",
    "eventV1CalendarOpening": "Takvimin açılıyor…",
    "eventV1CalendarFailed": "Takvimin açılamadı. Tekrar deneyebilirsin.",
    "eventV1MapOpening": "Mekân haritada açılıyor…",
    "eventV1MapFailed": "Harita açılamadı. Tekrar deneyebilirsin.",
    "eventV1ReminderPush": "Gideceğin bir etkinlik yakında başlıyor.",
    "eventV1ChangedPush": "Tercih belirttiğin bir etkinlik güncellendi.",
    "eventV1CancelledPush": "Tercih belirttiğin bir etkinlik iptal edildi.",
    "eventV1TimeZone": "Saatler {zone} saat diliminde gösterilir.",
    "eventV1ImageUnavailable": "Etkinlik görseli kullanılamıyor",
    "eventV1ListChoice": "Tercihin: {choice}",
    "navProfile": "Profil",
    "navMessages": "Mesajlar",
    "navNearby": "Yakındakiler",
    "navEvents": "Etkinlikler",
    "retry": "Tekrar dene"
  }
};
